name: Build Executable

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install pyinstaller
        pip install pygame
        
    - name: Build Executable
      run: |
        pyinstaller  --icon Pacman.png --add-data "chest.png;." --add-data "Clyde.png;." --add-data "Inky.png;." --add-data "Pacman.png;." --add-data "Pinky.png;." --add-data "Player.png;." --add-data "rock.png;." --add-data "Blinky.png;." --noconsole --onefile BossBattles.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ScatterMaker
        path: ./dist/BossBattles.exe